apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasttech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fasttech
  template:
    metadata:
      labels:
        app: fasttech
    spec:
      containers:
        - name: fasttech
          image: fasttech/fasttech-api:latest
          ports:
            - containerPort: 8080
